config/routes.rb
Rails.application.routes.draw do
  
  resources :tenants do
    resources :projects
  end
  resources :members
  get 'home/index'
  root :to => "home#index"

  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => {
    :registrations => "milia/registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions",
    :passwords => "milia/passwords",
  }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :tenant
  validates_uniqueness_of :title
  validate :free_plan_user_number

  def free_plan_user_number
    if self.new_record? && (tenant.projects.count > 0) && (tenant.plan == 'free')
      errors.add(:base, "Free plans cannot have more than one project")
    end
  end

  def self.by_plan_and_tenant(tenant_id)
    tenant = Tenant.find(tenant_id)
    if tenant.plan == 'premium'
      tenant.projects
    else
      tenant.projects.order(:id).limit(1)
    end
  end


end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_tenant, only: [:show, :edit, :update, :destory, :create , :new]
  #before_action :verify_tenant



  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
    #@tenant = Tenant.find(params[:tenant_id])
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to root_url, notice: 'Project was successfully created.' }
      else
        format.html { render :new  }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to root_url, notice: 'Project was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to root_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:title, :details, :expected_complition_date, :tenant_id)
    end

    def set_tenant
      @tenant = Tenant.first
    end

    def verify_tenant
      unless params[:tenant_id] == Tenant.current_tenant.id.to_s
        redirect_to :root, flash: { error: 'You are not autorized to access this project'}
      end
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for [:tenant, @project] do |f|%>
  <% if @project.errors.any? %>
    <div id="error_explanation " class="bg-warning">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title   %>
    <%= f.text_field :title , class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_field :details, class: "form-control"  %>
  </div>

  <div class="form-group">
    <%= f.label :expected_complition_date %>
    <%= f.date_select :expected_complition_date, class: "form-control datepicker"  %>
  </div>

  <div class="control-group">
    <button class="btn btn-primary" type="submit">
    Create project
    </button>
  </div>

  <br>
  <%= f.hidden_field :tenant_id, value: params[:tenant_id],  class: "form-control"%>

<% end %>

app/views/projects/_list.html.erb
<%- model_class = Project -%>

<h1>Projects</h1>

<table class="table ">
  <thead>
    <tr>
      <th scope="col ">Title</th>
      <th scope="col">Details</th>
      <th scope="col">Expected complition date</th>
      <th scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.details %></td>
        <td><%= project.expected_complition_date %></td>
        <td  style="text-align: right;"><%= link_to 'Show', tenant_project_path(project, tenant_id: @tenant.id) %> |
        <%= link_to 'Edit', edit_tenant_project_path(project, tenant_id: @tenant.id)  %> |
        <%= link_to 'Destroy', tenant_project_path(project, tenant_id: @tenant.id) , method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%if @tenant.can_create_project? %>
  <%= link_to 'New Project', new_tenant_project_path(tenant_id: @tenant.id) %>
<%end%>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', tenant_project_path(@project, tenant_id: @tenant.id)  %> |
<%= link_to 'Back', root_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', :tenant => @tenant %>

<%= link_to 'Back', root_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Details:</strong>
  <%= @project.details %>
</p>

<p>
  <strong>Expected complition date:</strong>
  <%= @project.expected_complition_date %>
</p>


<%= link_to 'Edit', edit_tenant_project_path(@project, tenant_id: @tenant.id) %> |
<%= link_to 'Back', root_path %>