config/routes.rb
Rails.application.routes.draw do
  
  resources :tenants do
    resources :projects
  end
  resources :members
  get 'home/index'
  root :to => "home#index"

  # *MUST* come *BEFORE* devise's definitions (below)
  as :user do
    match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end

  devise_for :users, :controllers => {
    :registrations => "milia/registrations",
    :confirmations => "confirmations",
    :sessions => "milia/sessions",
    :passwords => "milia/passwords",
  }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Saas" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]> <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script> <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary  border-bottom box-shadow d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3">
      <div class='container'>
        <a class="navbar-brand" style='  text-decoration: underline;' href="/">MyPMA</a>
        <div class="collapse navbar-collapse">
          <ul class="navbar-nav mr-auto mt-2 mt-lg-0 ">
            <li class="nav-item">
              <a>
                <%= link_to "<i class='fa fa-dollar'></i> Priceing".html_safe, '#', class: "btn btn-outline-light mr-10" %></a>
            </li>
            <% if current_user %><% end %>
          </ul>
          <ul class=" navbar-nav  mt-2 mt-lg-0">
            <%if !current_user%>
              <li class="nav-item ">
                <a>
                  <%= link_to "<i class='fa fa-dollar'></i> Sign In".html_safe, user_session_path, class: "btn btn-success mr-10" %></a>
              </li>
              <li class="nav-item">
                <a>
                  <%= link_to "<i class='fa fa-dollar'></i> Sign Up".html_safe, new_member_path , class: "btn btn-warning mr-10" %></a>
              </li>
            <%else%>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  <%=current_user.email%>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" style="padding : 0px">
                  <a>

                      <%= link_to "<i class='fa fa-users'></i> Add Members".html_safe, new_member_path, class: "dropdown-item", style: "width:100%" %>

                  </a>
                  <a class="dropdown-item" href="#">Another action</a>
                  <div class="dropdown-divider" style="margin-bottom : 0px"></div>
                  <a><%= link_to "Sign out".html_safe, destroy_user_session_path, class: ' btn btn-danger' , style: "width:100%", :method => :delete %>
                  </a>
                </div>
              </li>
              <button type="button" class="btn btn-primary" data-toggle="popover" data-trigger="hover" title='Company: <%=Tenant.current_tenant.name%>' data-content='Plan: <%=Tenant.current_tenant.plan.capitalize%>'><i class='fa fa-info'></i> </button>
            <%end%>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <div class="row justify-content-md-center">
        <div class="col-lg-10">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>
    </div>

    <!--/row-->

    <footer class="footer">
      <div class="container">
        <div class="row justify-content-md-center">
          <span class="text-muted">@ Egor Sidorov</span>
        </div>
      </div>
    </footer>

  </body>
</html>